import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ErrorBoundary({ error }: { error: Error }) {
  return (
    <html lang="en">
      <body style={{ padding: 32, color: 'red' }}>
        <h1>Something went wrong</h1>
        <pre>{error.message}</pre>
        <p>Please check your environment variables and server logs.</p>
      </body>
    </html>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <header style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center', padding: '1rem', gap: '1rem', height: '4rem' }}>
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <ErrorBoundaryWrapper>{children}</ErrorBoundaryWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}

// Minimal error boundary wrapper for React (client component)
'use client';
import { useEffect, useState } from 'react';
function ErrorBoundaryWrapper({ children }: { children: React.ReactNode }) {
  const [error, setError] = useState<Error | null>(null);
  useEffect(() => {
    const handleError = (event: ErrorEvent) => {
      setError(event.error || new Error('Unknown error'));
    };
    window.addEventListener('error', handleError);
    return () => window.removeEventListener('error', handleError);
  }, []);
  if (error) return <ErrorBoundary error={error} />;
  return <>{children}</>;
}
